//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Txooo.Mobile.SysSmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://internalservice.txooo.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://internalservice.txooo.com/", ConfigurationName="SysSmsService.SysSmsServiceSoap")]
    public interface SysSmsServiceSoap {
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 GetAccountInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/GetAccountInfo", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.GetAccountInfoResponse GetAccountInfo(Txooo.Mobile.SysSmsService.GetAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/GetAccountInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetAccountInfoResponse> GetAccountInfoAsync(Txooo.Mobile.SysSmsService.GetAccountInfoRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 GetReplyInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/GetReplyInfo", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.GetReplyInfoResponse GetReplyInfo(Txooo.Mobile.SysSmsService.GetReplyInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/GetReplyInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetReplyInfoResponse> GetReplyInfoAsync(Txooo.Mobile.SysSmsService.GetReplyInfoRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/ChaotangTestSms", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse ChaotangTestSms(Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/ChaotangTestSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse> ChaotangTestSmsAsync(Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendOfficeSms", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.SendOfficeSmsResponse SendOfficeSms(Txooo.Mobile.SysSmsService.SendOfficeSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendOfficeSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendOfficeSmsResponse> SendOfficeSmsAsync(Txooo.Mobile.SysSmsService.SendOfficeSmsRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 mobiles 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendBatchOfficeSms", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse SendBatchOfficeSms(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendBatchOfficeSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse> SendBatchOfficeSmsAsync(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendWebUserSms", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.SendWebUserSmsResponse SendWebUserSms(Txooo.Mobile.SysSmsService.SendWebUserSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendWebUserSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendWebUserSmsResponse> SendWebUserSmsAsync(Txooo.Mobile.SysSmsService.SendWebUserSmsRequest request);
        
        // CODEGEN: 命名空间 http://internalservice.txooo.com/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendLeavewordCheckSms", ReplyAction="*")]
        Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse SendLeavewordCheckSms(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://internalservice.txooo.com/SendLeavewordCheckSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse> SendLeavewordCheckSmsAsync(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfo", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.GetAccountInfoRequestBody Body;
        
        public GetAccountInfoRequest() {
        }
        
        public GetAccountInfoRequest(Txooo.Mobile.SysSmsService.GetAccountInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAccountInfoRequestBody {
        
        public GetAccountInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfoResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.GetAccountInfoResponseBody Body;
        
        public GetAccountInfoResponse() {
        }
        
        public GetAccountInfoResponse(Txooo.Mobile.SysSmsService.GetAccountInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class GetAccountInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccountInfoResult;
        
        public GetAccountInfoResponseBody() {
        }
        
        public GetAccountInfoResponseBody(string GetAccountInfoResult) {
            this.GetAccountInfoResult = GetAccountInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReplyInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReplyInfo", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.GetReplyInfoRequestBody Body;
        
        public GetReplyInfoRequest() {
        }
        
        public GetReplyInfoRequest(Txooo.Mobile.SysSmsService.GetReplyInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetReplyInfoRequestBody {
        
        public GetReplyInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReplyInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReplyInfoResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.GetReplyInfoResponseBody Body;
        
        public GetReplyInfoResponse() {
        }
        
        public GetReplyInfoResponse(Txooo.Mobile.SysSmsService.GetReplyInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class GetReplyInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReplyInfoResult;
        
        public GetReplyInfoResponseBody() {
        }
        
        public GetReplyInfoResponseBody(string GetReplyInfoResult) {
            this.GetReplyInfoResult = GetReplyInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChaotangTestSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChaotangTestSms", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.ChaotangTestSmsRequestBody Body;
        
        public ChaotangTestSmsRequest() {
        }
        
        public ChaotangTestSmsRequest(Txooo.Mobile.SysSmsService.ChaotangTestSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class ChaotangTestSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string exnumber;
        
        public ChaotangTestSmsRequestBody() {
        }
        
        public ChaotangTestSmsRequestBody(string mobile, string msg, string exnumber) {
            this.mobile = mobile;
            this.msg = msg;
            this.exnumber = exnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChaotangTestSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChaotangTestSmsResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.ChaotangTestSmsResponseBody Body;
        
        public ChaotangTestSmsResponse() {
        }
        
        public ChaotangTestSmsResponse(Txooo.Mobile.SysSmsService.ChaotangTestSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class ChaotangTestSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChaotangTestSmsResult;
        
        public ChaotangTestSmsResponseBody() {
        }
        
        public ChaotangTestSmsResponseBody(string ChaotangTestSmsResult) {
            this.ChaotangTestSmsResult = ChaotangTestSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOfficeSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOfficeSms", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendOfficeSmsRequestBody Body;
        
        public SendOfficeSmsRequest() {
        }
        
        public SendOfficeSmsRequest(Txooo.Mobile.SysSmsService.SendOfficeSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendOfficeSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SendOfficeSmsRequestBody() {
        }
        
        public SendOfficeSmsRequestBody(string mobile, string msg) {
            this.mobile = mobile;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOfficeSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOfficeSmsResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendOfficeSmsResponseBody Body;
        
        public SendOfficeSmsResponse() {
        }
        
        public SendOfficeSmsResponse(Txooo.Mobile.SysSmsService.SendOfficeSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendOfficeSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendOfficeSmsResult;
        
        public SendOfficeSmsResponseBody() {
        }
        
        public SendOfficeSmsResponseBody(string SendOfficeSmsResult) {
            this.SendOfficeSmsResult = SendOfficeSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBatchOfficeSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBatchOfficeSms", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequestBody Body;
        
        public SendBatchOfficeSmsRequest() {
        }
        
        public SendBatchOfficeSmsRequest(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendBatchOfficeSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Txooo.Mobile.SysSmsService.ArrayOfString mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SendBatchOfficeSmsRequestBody() {
        }
        
        public SendBatchOfficeSmsRequestBody(Txooo.Mobile.SysSmsService.ArrayOfString mobiles, string msg) {
            this.mobiles = mobiles;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBatchOfficeSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBatchOfficeSmsResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponseBody Body;
        
        public SendBatchOfficeSmsResponse() {
        }
        
        public SendBatchOfficeSmsResponse(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendBatchOfficeSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendBatchOfficeSmsResult;
        
        public SendBatchOfficeSmsResponseBody() {
        }
        
        public SendBatchOfficeSmsResponseBody(string SendBatchOfficeSmsResult) {
            this.SendBatchOfficeSmsResult = SendBatchOfficeSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWebUserSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWebUserSms", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendWebUserSmsRequestBody Body;
        
        public SendWebUserSmsRequest() {
        }
        
        public SendWebUserSmsRequest(Txooo.Mobile.SysSmsService.SendWebUserSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendWebUserSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SendWebUserSmsRequestBody() {
        }
        
        public SendWebUserSmsRequestBody(string mobile, string msg) {
            this.mobile = mobile;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWebUserSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWebUserSmsResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendWebUserSmsResponseBody Body;
        
        public SendWebUserSmsResponse() {
        }
        
        public SendWebUserSmsResponse(Txooo.Mobile.SysSmsService.SendWebUserSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendWebUserSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWebUserSmsResult;
        
        public SendWebUserSmsResponseBody() {
        }
        
        public SendWebUserSmsResponseBody(string SendWebUserSmsResult) {
            this.SendWebUserSmsResult = SendWebUserSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLeavewordCheckSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLeavewordCheckSms", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequestBody Body;
        
        public SendLeavewordCheckSmsRequest() {
        }
        
        public SendLeavewordCheckSmsRequest(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendLeavewordCheckSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msg;
        
        public SendLeavewordCheckSmsRequestBody() {
        }
        
        public SendLeavewordCheckSmsRequestBody(long lyId, string mobile, string msg) {
            this.lyId = lyId;
            this.mobile = mobile;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLeavewordCheckSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLeavewordCheckSmsResponse", Namespace="http://internalservice.txooo.com/", Order=0)]
        public Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponseBody Body;
        
        public SendLeavewordCheckSmsResponse() {
        }
        
        public SendLeavewordCheckSmsResponse(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://internalservice.txooo.com/")]
    public partial class SendLeavewordCheckSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendLeavewordCheckSmsResult;
        
        public SendLeavewordCheckSmsResponseBody() {
        }
        
        public SendLeavewordCheckSmsResponseBody(string SendLeavewordCheckSmsResult) {
            this.SendLeavewordCheckSmsResult = SendLeavewordCheckSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SysSmsServiceSoapChannel : Txooo.Mobile.SysSmsService.SysSmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SysSmsServiceSoapClient : System.ServiceModel.ClientBase<Txooo.Mobile.SysSmsService.SysSmsServiceSoap>, Txooo.Mobile.SysSmsService.SysSmsServiceSoap {
        
        public SysSmsServiceSoapClient() {
        }
        
        public SysSmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SysSmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysSmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysSmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.GetAccountInfoResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.GetAccountInfo(Txooo.Mobile.SysSmsService.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfo(request);
        }
        
        public string GetAccountInfo() {
            Txooo.Mobile.SysSmsService.GetAccountInfoRequest inValue = new Txooo.Mobile.SysSmsService.GetAccountInfoRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.GetAccountInfoRequestBody();
            Txooo.Mobile.SysSmsService.GetAccountInfoResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).GetAccountInfo(inValue);
            return retVal.Body.GetAccountInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetAccountInfoResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.GetAccountInfoAsync(Txooo.Mobile.SysSmsService.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetAccountInfoResponse> GetAccountInfoAsync() {
            Txooo.Mobile.SysSmsService.GetAccountInfoRequest inValue = new Txooo.Mobile.SysSmsService.GetAccountInfoRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.GetAccountInfoRequestBody();
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).GetAccountInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.GetReplyInfoResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.GetReplyInfo(Txooo.Mobile.SysSmsService.GetReplyInfoRequest request) {
            return base.Channel.GetReplyInfo(request);
        }
        
        public string GetReplyInfo() {
            Txooo.Mobile.SysSmsService.GetReplyInfoRequest inValue = new Txooo.Mobile.SysSmsService.GetReplyInfoRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.GetReplyInfoRequestBody();
            Txooo.Mobile.SysSmsService.GetReplyInfoResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).GetReplyInfo(inValue);
            return retVal.Body.GetReplyInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetReplyInfoResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.GetReplyInfoAsync(Txooo.Mobile.SysSmsService.GetReplyInfoRequest request) {
            return base.Channel.GetReplyInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.GetReplyInfoResponse> GetReplyInfoAsync() {
            Txooo.Mobile.SysSmsService.GetReplyInfoRequest inValue = new Txooo.Mobile.SysSmsService.GetReplyInfoRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.GetReplyInfoRequestBody();
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).GetReplyInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.ChaotangTestSms(Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest request) {
            return base.Channel.ChaotangTestSms(request);
        }
        
        public string ChaotangTestSms(string mobile, string msg, string exnumber) {
            Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest inValue = new Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.ChaotangTestSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            inValue.Body.exnumber = exnumber;
            Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).ChaotangTestSms(inValue);
            return retVal.Body.ChaotangTestSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.ChaotangTestSmsAsync(Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest request) {
            return base.Channel.ChaotangTestSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.ChaotangTestSmsResponse> ChaotangTestSmsAsync(string mobile, string msg, string exnumber) {
            Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest inValue = new Txooo.Mobile.SysSmsService.ChaotangTestSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.ChaotangTestSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            inValue.Body.exnumber = exnumber;
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).ChaotangTestSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.SendOfficeSmsResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendOfficeSms(Txooo.Mobile.SysSmsService.SendOfficeSmsRequest request) {
            return base.Channel.SendOfficeSms(request);
        }
        
        public string SendOfficeSms(string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendOfficeSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendOfficeSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendOfficeSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            Txooo.Mobile.SysSmsService.SendOfficeSmsResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendOfficeSms(inValue);
            return retVal.Body.SendOfficeSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendOfficeSmsResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendOfficeSmsAsync(Txooo.Mobile.SysSmsService.SendOfficeSmsRequest request) {
            return base.Channel.SendOfficeSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendOfficeSmsResponse> SendOfficeSmsAsync(string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendOfficeSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendOfficeSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendOfficeSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendOfficeSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendBatchOfficeSms(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest request) {
            return base.Channel.SendBatchOfficeSms(request);
        }
        
        public string SendBatchOfficeSms(Txooo.Mobile.SysSmsService.ArrayOfString mobiles, string msg) {
            Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequestBody();
            inValue.Body.mobiles = mobiles;
            inValue.Body.msg = msg;
            Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendBatchOfficeSms(inValue);
            return retVal.Body.SendBatchOfficeSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendBatchOfficeSmsAsync(Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest request) {
            return base.Channel.SendBatchOfficeSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendBatchOfficeSmsResponse> SendBatchOfficeSmsAsync(Txooo.Mobile.SysSmsService.ArrayOfString mobiles, string msg) {
            Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendBatchOfficeSmsRequestBody();
            inValue.Body.mobiles = mobiles;
            inValue.Body.msg = msg;
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendBatchOfficeSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.SendWebUserSmsResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendWebUserSms(Txooo.Mobile.SysSmsService.SendWebUserSmsRequest request) {
            return base.Channel.SendWebUserSms(request);
        }
        
        public string SendWebUserSms(string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendWebUserSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendWebUserSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendWebUserSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            Txooo.Mobile.SysSmsService.SendWebUserSmsResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendWebUserSms(inValue);
            return retVal.Body.SendWebUserSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendWebUserSmsResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendWebUserSmsAsync(Txooo.Mobile.SysSmsService.SendWebUserSmsRequest request) {
            return base.Channel.SendWebUserSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendWebUserSmsResponse> SendWebUserSmsAsync(string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendWebUserSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendWebUserSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendWebUserSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendWebUserSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendLeavewordCheckSms(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest request) {
            return base.Channel.SendLeavewordCheckSms(request);
        }
        
        public string SendLeavewordCheckSms(long lyId, string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequestBody();
            inValue.Body.lyId = lyId;
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse retVal = ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendLeavewordCheckSms(inValue);
            return retVal.Body.SendLeavewordCheckSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse> Txooo.Mobile.SysSmsService.SysSmsServiceSoap.SendLeavewordCheckSmsAsync(Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest request) {
            return base.Channel.SendLeavewordCheckSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsResponse> SendLeavewordCheckSmsAsync(long lyId, string mobile, string msg) {
            Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest inValue = new Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequest();
            inValue.Body = new Txooo.Mobile.SysSmsService.SendLeavewordCheckSmsRequestBody();
            inValue.Body.lyId = lyId;
            inValue.Body.mobile = mobile;
            inValue.Body.msg = msg;
            return ((Txooo.Mobile.SysSmsService.SysSmsServiceSoap)(this)).SendLeavewordCheckSmsAsync(inValue);
        }
    }
}
